### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by DuskStarGITHUB** [AutumnVN/AutumnVN#1]
IDK what i see, but please the size of your image is big, so big.

**Comment by AutumnVN** [comment]
if you mean the chino image
it's random and i don't think i can set max-height

**Comment by DuskStarGITHUB** [comment]
Yhea you can whit the property hight="sise-here" in your tag of your image.

**Comment by AutumnVN** [comment]
landscape-size image will be distorted if set fixed height, that's why i want max-height, but can't

**Comment by DuskStarGITHUB** [comment]
Okay
